### ISSUE TITLE
Parse Recipe into Ingredients

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/food-doods#122]
Right now the `ingredients` array in a `recipe` object consist of strings describing the ingredient. We want to map these descriptions to ingredients in the ingredient service database.

For example, we want to convert the following:

```
[
  "4 skinless, boneless chicken breast halves",
  "2 tablespoons butter",
  ...
]
```

To something like:

```
[
  {
    id: 50,
    quantity: 4,
    notes: "skinless, boneless halves"
  },
  {
    id: 101,
    quantity: 2
  }
]
```

Where `id` corresponds to the ingredient id in the ingredient service db. 

* The `quantity` should be converted to whatever the ingredient's default unit is. For example, if butter in the db is measured in `g`, then "2 tablespoons" should be converted to the equivalent in grams i.e. 30g, and stored appropriately.
* If the ingredient db doesn't contain the ingredient used in the recipe, it should be added to the ingredient db first (Correct me on this @DConnorFong).

This should be done *after* the recipe scraper is done but *before* the recipe gets saved into the db. We can start by extending the script to seed the ingredient database (in `ingredient/init/init.ts`), which already parses a very similar ingredient format.

**Mapping recipes to ingredients**

After we parse an ingredient, we get something like `{ name: 'chicken', ... }`. We want to check in the ingredient db if it has an ingredient with this name or not. If it does, we want to return its id then *attach* it to the object. After this the object should look like:

```
{
  id: 100 (or whatever the id is),
  name: 'chicken',
  ...
}
```

Right now the ingredient service isn't deployed so we can check this by running the script in `ingredient/init/init.ts` (or importing the function and running it against the `seed.json` file there).

I'm not sure what to do in the case it doesn't exist in the db. I think for now we can generate a random id then add it to the ingredient db.

**TODOS**

At the time of writing, the ingredients for each recipe has been parsed in a similar way to the `seed.json` file. This means each ingredient object has a `name` and `unit_category` field.

We want to expand this for recipes by adding a `quantity` field for each ingredient. This means adjusting the parser to check for how much of each ingredient is being used.

- [ ] Update ingredient parser to check for quantity
- [ ] Fetch ID of ingredient from ingredient db then attach it to parsed objects
- [ ] Save recipes with this new ingredient format to db
